[project]
name = "cdk-linter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fire>=0.7.1",
    "msgspec>=0.21.1",
    "tree-sitter>=0.25.2",
    "tree-sitter-typescript>=0.23.2",
]

[project.scripts]
linter = "cdk_linter.runner:run"
dev = "cdk_linter.dev:run"
clean = "cdk_linter.dev:clean"
tsparser = "cdk_linter.parsers.tsparser:main"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "black>=26.3.1",
]
