[project]
name = "cdk-linter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fire>=0.7.1",
    "graphviz>=0.21",
    "msgspec>=0.21.1",
    "tree-sitter>=0.25.2",
    "tree-sitter-typescript>=0.23.2",
]

[project.scripts]
linter = "cdk_linter.runner:run"
dev = "cdk_linter.dev:run"
clean = "cdk_linter.dev:clean"
tsparser = "cdk_linter.parsers.ts_parser:main"

[dependency-groups]
dev = [
    "autoflake>=2.3.0",
    "black>=26.3.1",
    "isort>=5.13.0",
]

[tool.uv]
package = true

[tool.black]
line-length = 100
target-version = ["py312"]
extend-exclude = "data"

[tool.isort]
profile = "black"
line_length = 100
skip = ["data"]

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
